name: 'post-loan'

template: "您需要根据贷款场景对话内容提供最佳答案，从该问题的选项（A,B,C,D,E,F）中选择三个最优选项，从最佳到最差排列。\n不要编写任何内容，只需要返回选项字母。返回结果格式：\n\n答案 = ['.', '.', '.']\n\n```对话内容```\n\n{}\n\n\n```选项```\n{}\n"

options: "A. 客户已经还款\nB. 客户承诺三天内还款\nC. 客户承诺超三天，有明确时间\nD. 客户承诺超三天后还款，但无明确时间，包括跳票\nE. 客户还款困难\nF. 客户回答意图未知\n"
